title: Working in IT
description: Recovering technology addict still working in IT. PowerShell, Systems Center, infrastructure in a Windows world. Personally, I use Linux.
theme: jekyll-theme-minimal
twitter:
 url: https://twitter.com/kbstarmie
 username: "@kbstarmie"
email: "mail@kbstarmie.io"
pgp: "0x84ACE6C3"
